### ISSUE TITLE
ModuleNotFoundError: No module named 'zoneinfo'

### ISSUE THREAD

**Issue by karlh626** [jspricke/remind-caldav#14]
Hello, I was excited to run accross this utility which I hope to use to sync remind with my nextcloud calendar.

I am getting the following errors however when I install using pip3 or python3 setup:

`$  rem2dav
Traceback (most recent call last):
  File "/usr/local/bin/rem2dav", line 11, in <module>
    load_entry_point('remind-caldav==0.8.0', 'console_scripts', 'rem2dav')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/remind_caldav-0.8.0-py3.8.egg/rem2dav.py", line 32, in <module>
  File "/home/karl/.local/lib/python3.8/site-packages/remind.py", line 29, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'`

I am running: Ubuntu 20.04.3 LTS

I would be most appreciateive of any suggestions of what I might be missing.

**Comment by jspricke** [comment]
Hi Karl,

>ModuleNotFoundError: No module named 'zoneinfo'`
>
>I am running: Ubuntu 20.04.3 LTS

zoneinfo is in Python 3.9, whereas Ubuntu 20.04 has Python 3.8. The 
previous release of python-remind should work:

pip install remind==0.17.0

**Comment by karlh626** [comment]
Thank you very much for your extremly quick and helpful response!  Your suggestion worked perfectly.

Thank you again!
