### ISSUE TITLE
caldav.lib.error.ReportError: ReportError at '415 Unsupported Media Type

### ISSUE THREAD

**Issue by delightfulagony** [jspricke/remind-caldav#18]
I can't seem to connect a CalDav calendar using this program. I've been trying to make sense of the error log but I can't find the issue.

## Command
```
$ dav2rem -r https://[redacted]/remote.php/dav -u [redacted] -p [redacted] ~/.config/remind/remind.txt
```

## Error log
```
Traceback (most recent call last):
  File "/home/agony/.local/bin/dav2rem", line 8, in <module>
    sys.exit(main())
  File "/home/agony/.local/lib/python3.9/site-packages/dav2rem.py", line 90, in main
    for event in calendar.events()
  File "/home/agony/.local/lib/python3.9/site-packages/caldav/objects.py", line 1063, in events
    return self.search(root, comp_class=Event)
  File "/home/agony/.local/lib/python3.9/site-packages/caldav/objects.py", line 812, in search
    (response, objects) = self._request_report_build_resultlist(xml, comp_class)
  File "/home/agony/.local/lib/python3.9/site-packages/caldav/objects.py", line 779, in _request_report_build_resultlist
    response = self._query(xml, 1, 'report')
  File "/home/agony/.local/lib/python3.9/site-packages/caldav/objects.py", line 167, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.ReportError: ReportError at '415 Unsupported Media Type

b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>Sabre\\DAV\\Exception\\ReportNotSupported</s:exception>\n  <s:message/>\n  <d:supported-report/>\n</d:error>\n'', reason no reason
```

## Version
- Python: `Python 3.9.13`
- Remind: `REMIND 03.03.05 (English version)`
- Remind-Caldav: `Version: 0.8.0`
- Nextcloud (Where I'm syncing from): `22.2.7`

## Additional info
- Remind-Caldav installed via `pip install --user remind-caldav`
- Linux version: `5.15.16`
- Linux distribution: Gentoo

**Comment by delightfulagony** [comment]
The URL was missing user and calendar, solved by adding `/<user>/<calendar>` to the URL
