### ISSUE TITLE
rem2dav: "JSONDecodeError: Expecting value"

### ISSUE THREAD

**Issue by R-7200** [jspricke/remind-caldav#20]
Hi!

Today I installed remind-caldav via pip3.11 from pkgsrc on Darwin but receive the following, no matter how simple the .reminders file is:

`Darwin Mac-mini-von-Manuel.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64`

```
mk ~ $ rem2dav -r sync.infomaniak.com .reminders
Traceback (most recent call last):
  File "/Users/mk/pkgsrc/pkg/bin/rem2dav", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/site-packages/rem2dav.py", line 96, in main
    vobject = remind.to_vobject()
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/site-packages/remind.py", line 336, in to_vobject
    self._update()
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/site-packages/remind.py", line 263, in _update
    self._reminders = self._parse_remind(self._filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/site-packages/remind.py", line 110, in _parse_remind
    for month in loads(process.stdout):
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mk/pkgsrc/pkg/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

What now?

Best wishes.

**Comment by jspricke** [comment]
Which remind version do you have? Can you try a newer version?

**Comment by R-7200** [comment]
pkgsrc currently has remind-03.02.00. After manually downloading & compiling remind-04.02.09, rem2dav works flawlessly. I'll update pkgsrc's remind. I'll update pkgsrc's remind.
