### ISSUE TITLE
update dav2rem.py to python3

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [jspricke/remind-caldav#5]
```
% diff -Naur remind-caldav/dav2rem.py remind-caldav-new/dav2rem.py
--- remind-caldav/dav2rem.py	2019-01-16 17:48:26.932515622 +0300
+++ remind-caldav-new/dav2rem.py	2019-01-16 17:38:02.816858506 +0300
@@ -24,7 +24,7 @@
 from netrc import netrc
 from os.path import basename, expanduser, splitext
 from remind import Remind
-from urlparse import urlparse
+#from urllib.parse import urllib.parse
 # pylint: disable=maybe-no-member
 
 
@@ -52,7 +52,7 @@
         passwd = args.davpass
     else:
         try:
-            (user, _, passwd) = netrc().authenticators(urlparse(args.davurl).netloc)
+            (user, _, passwd) = netrc().authenticators(urllib.parse(args.davurl).netloc)
         except (IOError, TypeError):
             if not args.davuser:
                 print('dav2rem: Error, argument -u/--davuser or netrc is required')
@@ -60,7 +60,7 @@
             user = args.davuser
             try:
                 from keyring import get_password
-                passwd = get_password(urlparse(args.davurl).netloc, user)
+                passwd = get_password(urllib.parse(args.davurl).netloc, user)
             except ImportError:
                 passwd = None
             if not passwd:
```

**Comment by c-e-p-x-u-o** [comment]
```
% dav2rem -r URL -u USER -p PASS -
Traceback (most recent call last):
  File "/usr/local/bin/dav2rem", line 11, in <module>
    load_entry_point('remind-caldav==0.6.0', 'console_scripts', 'dav2rem')()
  File "/usr/local/lib/python3.7/dist-packages/remind_caldav-0.6.0-py3.7.egg/dav2rem.py", line 80, in main
AttributeError: 'dict' object has no attribute 'viewkeys'
```

**Comment by jspricke** [comment]
Please send a pull request.

**Comment by c-e-p-x-u-o** [comment]
The patch above corrects only the urlparse error.

After it got another dict error. (specified above)

Looks like ```viewkeys``` should be replaced with ```items```.

After this correction I got another ```KeyError: ('KEY', Event(URL/KEY.ics))```

**Comment by c-e-p-x-u-o** [comment]
Anyway, this issue is not about "apply my patch", but about "update dav2rem.py to python3".
rem2dav.py is python3 dav2rem.py is python2, Please make project consistent.

**Comment by c-e-p-x-u-o** [comment]
Please reopen.

**Comment by jspricke** [comment]
I don't have a need for a Python 3 version of `dav2rem` right now, so I will not work no it. But as you started to work on it, I offer to help if you send it as a pull request.

**Comment by c-e-p-x-u-o** [comment]
https://github.com/jspricke/remind-caldav/pull/8

**Comment by c-e-p-x-u-o** [comment]
but now it says 'KeyError'

**Comment by sverona** [comment]
This still needs to be pushed to pip.

**Comment by jspricke** [comment]
@sverona done now with v0.7.0. Thanks for the reminder!
