### ISSUE TITLE
rem2dav.py 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [jspricke/remind-caldav#6]
```
% echo 'REM 1 -1 AT 20:00 MSG qwe' | rem2dav -r URL -u USER -p PASS -

Traceback (most recent call last):
  File "/usr/local/bin/rem2dav", line 11, in <module>
    load_entry_point('remind-caldav==0.6.0', 'console_scripts', 'rem2dav')()
  File "/usr/local/lib/python3.7/dist-packages/remind_caldav-0.6.0-py3.7.egg/rem2dav.py", line 63, in main
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by jspricke** [comment]
This is Python 2 code.

**Comment by c-e-p-x-u-o** [comment]
Thank you, now it's Python 3 code.
